language: java
jdk:
  - oraclejdk8
notification:
  email:
    recipients:
      - mfcliu@gmail.com
    on_success: always
    on_failure: always

before_script:
  - echo "MAVEN_OPTS='-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m'" > ~/.mavenrc

before_install:
  - pip install --user codecov

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken="${COVERALLS_TOKEN}"

branches:
  only:
    - master

env:
  global:
   - secure: "sXqIEilRlXlX/4ZgpqfSvTzeI5GnbKkTXxHb/qXpHysMg1LHr0hzEC3grnqggS5na/bXYQG/4orV2sM3edMEgdBIPb5BBwRP2cYtOdzgbqAbQeDZZ54bjU3wzABUKGSvgJmeu9G4/vZL0zJq/wn7UOLDf2+xwMJM8IhmKpNApS9IvTjoqd9tqQBeswgOAucwvQiuXTaKa/KkL3TlQYwa4aaYFz01HTqhqoWYENy/+NoPwBSCC+ZKTCTBxNouP81ejaIODUL5jorcKemRZpdeMKKIbn65jMVw/g1yi9OldY9BV+AxCfCByOlNCtn3xD118kVeOaHh7D6wiuPO4lfiohzwq9Ig6fYgQI1tDRaq75tBk9gNGzM0lXq2eHLW9ogXLqKDb4FdXCoMc3H2fCFnUQ3WI+hP15o41XOrr/NIPz+l2ymU3SvcIGMJzJvgzkDxFk2t+ONShJ9Kg11hucoH1IevvclDE49mZqXf/hJvU4TtO8rYcTgwT+tPxTS2HjlkDImll2MbN4ONz5LWLToEM7rZrSWiAxeA253bG9p4EyjBzqfb4zPKEeHUJUKQMCryPUnChRXBD4WWp57juH/E3yB5PzY03ju/rTsfBlK0snfhhlrlK0ocQ0OJ8cmU2x7aOtDk018v06i63b5w5DcIgA6xXE5/03SSwExXV4DmCrg="
   - "MAVEN_OPTS=-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m"

#addons:
#  coverity_scan:
#    project:
#      name: "mfcliu/demo_opensource"
#      description: "Build submitted via Travis CI"
#    notification_email: mfcliu@gmail.com
#    build_command_prepend: "mvn clean"
#    build_command: "mvn -DskipTests=true compile"
#    branch_pattern: master

cache:
  directories:
  - $HOME/.m2
